# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: R
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
env:
  global:
    - NOT_CRAN: false
addons:
  apt:
    packages:
      libxml2
